services:
  postgres-authentication:
    image: postgres:16-alpine
    ports:
      - 1101:5432
    volumes:
      - uservice_authentication_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  uservice_authentication_postgres:
