// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-authentication/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateUserService is an autogenerated mock type for the UpdateUserService type
type MockUpdateUserService struct {
	mock.Mock
}

type MockUpdateUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUserService) EXPECT() *MockUpdateUserService_Expecter {
	return &MockUpdateUserService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, token, user
func (_m *MockUpdateUserService) Exec(ctx context.Context, token string, user *models.UpdateUser) (*models.User, error) {
	ret := _m.Called(ctx, token, user)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UpdateUser) (*models.User, error)); ok {
		return rf(ctx, token, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UpdateUser) *models.User); ok {
		r0 = rf(ctx, token, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.UpdateUser) error); ok {
		r1 = rf(ctx, token, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateUserService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpdateUserService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - user *models.UpdateUser
func (_e *MockUpdateUserService_Expecter) Exec(ctx interface{}, token interface{}, user interface{}) *MockUpdateUserService_Exec_Call {
	return &MockUpdateUserService_Exec_Call{Call: _e.mock.On("Exec", ctx, token, user)}
}

func (_c *MockUpdateUserService_Exec_Call) Run(run func(ctx context.Context, token string, user *models.UpdateUser)) *MockUpdateUserService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.UpdateUser))
	})
	return _c
}

func (_c *MockUpdateUserService_Exec_Call) Return(_a0 *models.User, _a1 error) *MockUpdateUserService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateUserService_Exec_Call) RunAndReturn(run func(context.Context, string, *models.UpdateUser) (*models.User, error)) *MockUpdateUserService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateUserService creates a new instance of MockUpdateUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUserService {
	mock := &MockUpdateUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
