// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-authentication/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthenticateService is an autogenerated mock type for the AuthenticateService type
type MockAuthenticateService struct {
	mock.Mock
}

type MockAuthenticateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticateService) EXPECT() *MockAuthenticateService_Expecter {
	return &MockAuthenticateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, token
func (_m *MockAuthenticateService) Exec(ctx context.Context, token string) (*models.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthenticateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockAuthenticateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthenticateService_Expecter) Exec(ctx interface{}, token interface{}) *MockAuthenticateService_Exec_Call {
	return &MockAuthenticateService_Exec_Call{Call: _e.mock.On("Exec", ctx, token)}
}

func (_c *MockAuthenticateService_Exec_Call) Run(run func(ctx context.Context, token string)) *MockAuthenticateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthenticateService_Exec_Call) Return(_a0 *models.User, _a1 error) *MockAuthenticateService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthenticateService_Exec_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockAuthenticateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthenticateService creates a new instance of MockAuthenticateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticateService {
	mock := &MockAuthenticateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
